In [5]:
#  create a dirty dataset
import pandas as pd

data = {
    "Customer_ID": [101, 102, 103, 104, 104, 105, None],
    "Name": ["Amit", "Sneha", "Rahul", "Priya", "Priya", "Rohit", "Meera"],
    "Age": [25, None, 35, 29, 29, 40, 22],
    "City": ["Delhi", "Mumbai", None, "Delhi", "Delhi", "Chennai", "Chennai"],
    "Purchase_Amount": [1200, 1500, None, 1800, 1800, 2200, 900]
}

df = pd.DataFrame(data)
df

   Customer_ID   Name   Age     City  Purchase_Amount
0        101.0   Amit  25.0    Delhi           1200.0
1        102.0  Sneha   NaN   Mumbai           1500.0
2        103.0  Rahul  35.0     None              NaN
3        104.0  Priya  29.0    Delhi           1800.0
4        104.0  Priya  29.0    Delhi           1800.0
5        105.0  Rohit  40.0  Chennai           2200.0
6          NaN  Meera  22.0  Chennai            900.0

In [6]:
#data overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      6 non-null      float64
 1   Name             7 non-null      object
 2   Age              6 non-null      float64
 3   City             6 non-null      object
 4   Purchase_Amount  6 non-null      float64
dtypes: float64(3), object(2)
memory usage: 412.0+ bytes

In [7]:
#Find any missing data in ther or not
df.isnull().sum()

Customer_ID        1
Name               0
Age                1
City               1
Purchase_Amount    1
dtype: int64

In [8]:
#Remove duplicates data
df = df.drop_duplicates()
df

   Customer_ID   Name   Age     City  Purchase_Amount
0        101.0   Amit  25.0    Delhi           1200.0
1        102.0  Sneha   NaN   Mumbai           1500.0
2        103.0  Rahul  35.0     None              NaN
3        104.0  Priya  29.0    Delhi           1800.0
5        105.0  Rohit  40.0  Chennai           2200.0
6          NaN  Meera  22.0  Chennai            900.0

In [9]:
#Handle missing customer Ids
df = df.dropna(subset=["Customer_ID"])
df

   Customer_ID   Name   Age     City  Purchase_Amount
0        101.0   Amit  25.0    Delhi           1200.0
1        102.0  Sneha   NaN   Mumbai           1500.0
2        103.0  Rahul  35.0     None              NaN
3        104.0  Priya  29.0    Delhi           1800.0
5        105.0  Rohit  40.0  Chennai           2200.0

In [13]:
df["City"].fillna("Unknown", inplace=True)
df

/tmp/ipython-input-384421964.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna("Unknown", inplace=True)
/tmp/ipython-input-384421964.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"].fillna("Unknown", inplace=True)

   Customer_ID   Name    Age     City  Purchase_Amount
0        101.0   Amit  25.00    Delhi           1200.0
1        102.0  Sneha  32.25   Mumbai           1500.0
2        103.0  Rahul  35.00  Unknown              NaN
3        104.0  Priya  29.00    Delhi           1800.0
5        105.0  Rohit  40.00  Chennai           2200.0

In [14]:
#Final clean dataset summary
df.describe()

       Customer_ID        Age  Purchase_Amount
count     5.000000   5.000000         4.000000
mean    103.000000  32.250000      1675.000000
std       1.581139   5.717298       427.200187
min     101.000000  25.000000      1200.000000
25%     102.000000  29.000000      1425.000000
50%     103.000000  32.250000      1650.000000
75%     104.000000  35.000000      1900.000000
max     105.000000  40.000000      2200.000000